#!/usr/bin/env python3
"""
detect-references.py
Locate references to v4.x persisted ``specification/*_design.md`` files and
classify them into core-standard references (safe to propose a rewrite for) and
project-specific ones (reported for manual handling only).
Used by /migrate-design-to-adr skill.

Deterministic extraction lives here so the skill only reads the result (A-002).
"""

import argparse
import fnmatch
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

# Shared modules live in plugins/sdd-workflow/scripts (three levels up + scripts).
sys.path.insert(0, str(Path(__file__).resolve().parents[3] / "scripts"))
from fm_parser import find_front_matter_bounds  # noqa: E402
from naming import feature_name, has_spec_suffix, is_design_stem  # noqa: E402
from doc_walker import iter_all_markdown, iter_legacy_design_docs  # noqa: E402
from hook_common import (  # noqa: E402
    SOURCE_EXTENSIONS,
    load_naming_ignore_patterns,
    load_sdd_paths,
    read_sdd_config_json,
    resolve_lang_and_root,
    resolve_project_root,
)
from env_export import rewrite_exports  # noqa: E402

# Categories reported per reference.
CORE_STANDARD = "core_standard"
PROJECT_SPECIFIC = "project_specific"

# Generated or historical files: never rewritten, never listed as manual work.
# AI-SDD-PRINCIPLES.md / MIGRATION_PENDING.md / UPDATE_REQUIRED.md are
# regenerated by the session-start hook, and a CHANGELOG records history.
UNTOUCHABLE_NAMES = (
    "AI-SDD-PRINCIPLES.md",
    "MIGRATION_PENDING.md",
    "UPDATE_REQUIRED.md",
)
# A CHANGELOG in any language variant (CHANGELOG.md, CHANGELOG.ja.md, ...).
UNTOUCHABLE_PREFIX = "CHANGELOG"

# Front matter keys defined by the core schema (shared/references/front_matter_reference.md).
KNOWN_FM_KEYS = {
    "id", "title", "type", "status", "created", "updated", "sdd-version",
    "sdd-phase", "depends-on", "tags", "category", "priority", "risk",
    "impl-status", "ticket", "supersedes", "superseded-by",
}

# Code files scanned for in-comment references (detection only). The extension
# list is hook_common.SOURCE_EXTENSIONS so every skill agrees on what code is.
SKIP_DIR_NAMES = {
    ".git", ".cache", "node_modules", "venv", ".venv", "target", "build",
    "dist", "out", "coverage", "vendor", "__pycache__", ".idea",
    ".pytest_cache", ".mypy_cache", ".ruff_cache", ".tox", ".next", ".nuxt",
}

DESIGN_DRAFT_TOKEN = "design-draft"
# Every needle contains one of these, so a file holding neither can be skipped
# whole rather than line by line.
NEEDLE_MARKERS = ("_design", "design-")
ID_BOUNDARY = re.compile(r"[A-Za-z0-9_-]")
# Same key grammar as fm_parser.parse_front_matter, so a key is never "custom"
# here and known there.
FM_KEY = re.compile(r"^([A-Za-z][\w-]*):")
# A v5 draft id is ticket-scoped: design-123, or design-TICKET-123.
DRAFT_ID = re.compile(r"\bdesign-(\d+|[A-Z][A-Za-z0-9]*(-\d+)+)\b")
MARKDOWN_LINK = re.compile(r"\[[^\]]*\]\([^)]*\)")
RELATED_DESIGN_LABEL = re.compile(
    r"(related\s+design|design\s+doc|技術設計書|関連\s*design)", re.IGNORECASE
)


def log(message: str) -> None:
    """Print log message to stderr"""
    print(f"[detect-references] {message}", file=sys.stderr)


def is_untouchable(rel_path: str) -> bool:
    """Return True when the file must be left alone (generated or historical)."""
    parts = Path(rel_path).parts
    name = parts[-1] if parts else rel_path
    if name in UNTOUCHABLE_NAMES or name.startswith(UNTOUCHABLE_PREFIX):
        return True
    return ".cache" in parts


def matched_token(line: str, start: int, end: int) -> str:
    """Return the whitespace-delimited token surrounding a match."""
    left = start
    while left > 0 and not line[left - 1].isspace():
        left -= 1
    right = end
    while right < len(line) and not line[right].isspace():
        right += 1
    return line[left:right]


def is_design_draft_reference(token: str) -> bool:
    """Return True when a token points at the v5 ticket-scoped draft.

    ``task/{ticket-number}/design-draft.md`` and its ``design-{ticket-number}``
    id are correct v5 records, not migration targets.
    """
    if DESIGN_DRAFT_TOKEN in token:
        return True
    return bool(DRAFT_ID.search(token))


def find_matches(line: str, needle: str, require_id_boundary: bool):
    """Yield (start, end) of every occurrence of ``needle`` worth reporting."""
    start = 0
    while True:
        index = line.find(needle, start)
        if index == -1:
            return
        end = index + len(needle)
        start = end
        if require_id_boundary:
            before = line[index - 1] if index > 0 else ""
            after = line[end] if end < len(line) else ""
            if ID_BOUNDARY.match(before) or ID_BOUNDARY.match(after):
                continue
        yield index, end


def hierarchical_id(prefix: str, rel_dir: Path, feature: str) -> str:
    """Build ``{prefix}-{parent}-{feature}`` from the path under specification/."""
    parts = [p for p in rel_dir.parts if p not in ("", ".")]
    return "-".join([prefix] + parts + [feature])


def build_targets(spec_dir: Path, sdd_root: Path, adr_dir_name: str, feature: str) -> list:
    """Collect the v4.x design docs to migrate, with their adr/ counterparts."""
    targets = []
    for path in iter_legacy_design_docs(spec_dir):
        name = feature_name(path.stem)
        if feature and name != feature:
            continue
        rel_dir = path.parent.relative_to(spec_dir)
        adr_path = sdd_root / adr_dir_name / rel_dir / f"{name}.md"
        design_id = hierarchical_id("design", rel_dir, name)
        targets.append(
            {
                "feature": name,
                "design_path": str(path),
                "design_relative_path": str(path.relative_to(sdd_root)),
                "design_file_name": path.name,
                "design_id": design_id,
                "adr_relative_path": str(adr_path.relative_to(sdd_root)),
                "adr_id": hierarchical_id("adr", rel_dir, name),
                "references": [],
                # Searched per line. The relative path is not a needle: every
                # line containing it also contains the file name.
                "needles": ((path.name, False), (design_id, True)),
                "seen_lines": set(),
            }
        )
    return targets


def classify(rel_path: str, line: str, in_front_matter: bool, fm_key: str,
             paths, ignore_patterns) -> tuple:
    """Return (category, kind) for one reference occurrence."""
    parts = Path(rel_path).parts
    top = parts[0] if parts else ""
    name = parts[-1] if parts else rel_path

    if in_front_matter:
        if fm_key == "depends-on":
            return CORE_STANDARD, "front_matter_depends_on"
        if fm_key not in KNOWN_FM_KEYS:
            return PROJECT_SPECIFIC, "custom_front_matter_field"
        return PROJECT_SPECIFIC, "front_matter_field"

    if top == paths.specification_dir:
        stem = Path(name).stem
        if is_design_stem(stem):
            return PROJECT_SPECIFIC, "design_doc_cross_reference"
        if any(fnmatch.fnmatch(name, pattern) for pattern in ignore_patterns):
            # The project declared this document type itself, via
            # .sdd-config.json naming.ignore_patterns (e.g. `*_spec-test.md`).
            return PROJECT_SPECIFIC, "custom_document_type"
        if not (has_spec_suffix(stem) or "_" not in stem):
            # A stem carrying an undeclared suffix is not a core spec either.
            return PROJECT_SPECIFIC, "custom_document_type"
        if MARKDOWN_LINK.search(line) or RELATED_DESIGN_LABEL.search(line):
            return CORE_STANDARD, "spec_related_design_link"
        return PROJECT_SPECIFIC, "spec_prose_mention"

    if top == paths.requirement_dir:
        # PRD Non-Automation: only a link line may be proposed for rewrite.
        if MARKDOWN_LINK.search(line):
            return CORE_STANDARD, "prd_design_link"
        return PROJECT_SPECIFIC, "prd_prose_mention"

    if top == paths.adr_dir:
        # Reported so the mention is visible, never rewritten: adr/ is
        # append-only.
        return PROJECT_SPECIFIC, "adr_reference"

    if top == paths.task_dir:
        return PROJECT_SPECIFIC, "task_reference"

    if name.endswith(".md"):
        return PROJECT_SPECIFIC, "other_document_reference"
    return PROJECT_SPECIFIC, "code_comment"


def iter_scan_files(project_root: Path, sdd_root: Path, include_code: bool):
    """Yield ``(path, rel_path)`` for every file worth scanning.

    Markdown under the SDD root (relative to it), plus source files elsewhere in
    the project (relative to the project root) when requested.
    """
    for path in iter_all_markdown(sdd_root):
        yield path, str(path.relative_to(sdd_root))

    if not include_code:
        return

    # os.walk with in-place pruning so a skipped directory is never descended
    # into; rglob would stat every entry under node_modules first.
    for dirpath, dirnames, filenames in os.walk(project_root):
        dirnames[:] = sorted(d for d in dirnames if d not in SKIP_DIR_NAMES)
        current = Path(dirpath)
        if current == sdd_root:
            dirnames[:] = []
            continue
        for filename in sorted(filenames):
            path = current / filename
            if path.suffix in SOURCE_EXTENSIONS:
                yield path, str(path.relative_to(project_root))


def scan_file(path: Path, rel_path: str, targets: list, paths, ignore_patterns) -> None:
    """Record every reference in one file (at most one per line per target)."""
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return
    if not any(marker in text for marker in NEEDLE_MARKERS):
        return

    active = [t for t in targets if str(path) != t["design_path"]]
    if not active:
        return

    lines = text.splitlines()
    has_fm, closing_index = find_front_matter_bounds(lines)
    fm_key = ""

    for lineno, line in enumerate(lines, start=1):
        in_front_matter = has_fm and 1 < lineno <= closing_index
        if in_front_matter:
            key_match = FM_KEY.match(line)
            if key_match:
                fm_key = key_match.group(1)
        else:
            fm_key = ""

        key = (rel_path, lineno)
        for target in active:
            if key in target["seen_lines"]:
                continue
            for needle, boundary in target["needles"]:
                for start, end in find_matches(line, needle, boundary):
                    if is_design_draft_reference(matched_token(line, start, end)):
                        continue
                    category, kind = classify(
                        rel_path, line, in_front_matter, fm_key, paths, ignore_patterns,
                    )
                    target["seen_lines"].add(key)
                    target["references"].append(
                        {
                            "path": rel_path,
                            "line": lineno,
                            "text": line.strip(),
                            "category": category,
                            "kind": kind,
                            "matched": needle,
                        }
                    )
                    break
                if key in target["seen_lines"]:
                    break


def parse_args(argv: list) -> argparse.Namespace:
    parser = argparse.ArgumentParser(add_help=True)
    parser.add_argument("feature", nargs="?", default="")
    parser.add_argument("--all", action="store_true")
    parser.add_argument("--docs-only", action="store_true")
    return parser.parse_args(argv)


def main(argv=None) -> None:
    args = parse_args(sys.argv[1:] if argv is None else argv)
    if not args.feature and not args.all:
        log("ERROR: provide a feature name or --all")
        sys.exit(2)

    try:
        project_root = Path(resolve_project_root())
        raw_config = read_sdd_config_json(str(project_root))
        paths = load_sdd_paths(str(project_root), raw_config)
        ignore_patterns = load_naming_ignore_patterns(str(project_root), raw_config)
        lang, _ = resolve_lang_and_root(project_root)

        sdd_root = project_root / paths.root
        spec_dir = sdd_root / paths.specification_dir
        output_dir = sdd_root / ".cache" / "migrate-design-to-adr"
        output_dir.mkdir(parents=True, exist_ok=True)

        targets = build_targets(spec_dir, sdd_root, paths.adr_dir, args.feature)
        log(f"Migration targets: {len(targets)}")

        for path, rel_path in iter_scan_files(project_root, sdd_root, not args.docs_only):
            if is_untouchable(rel_path):
                continue
            scan_file(path, rel_path, targets, paths, ignore_patterns)

        for target in targets:
            # Scan-only bookkeeping, not part of the reported schema.
            del target["needles"], target["seen_lines"]
            target["core_standard_count"] = sum(
                1 for r in target["references"] if r["category"] == CORE_STANDARD
            )
            target["project_specific_count"] = sum(
                1 for r in target["references"] if r["category"] == PROJECT_SPECIFIC
            )

        result = {
            "scan_timestamp": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "mode": "single" if args.feature else "all",
            "total_targets": len(targets),
            "total_references": sum(len(t["references"]) for t in targets),
            "targets": targets,
        }

        detection_result = output_dir / "reference_detection.json"
        with open(detection_result, "w", encoding="utf-8") as f:
            json.dump(result, f, ensure_ascii=False, indent=2)
            f.write("\n")

        log(f"References found: {result['total_references']}")

        wrote = rewrite_exports("MIGRATE_ADR_", [
            f'export MIGRATE_ADR_CACHE_DIR="{output_dir}"',
            f'export MIGRATE_ADR_DETECTION_RESULT="{detection_result}"',
            f'export SDD_LANG="{lang}"',
        ])
        if wrote:
            log("Environment variables exported to CLAUDE_ENV_FILE")

        log(f"Results saved to: {detection_result}")

    except Exception as e:  # noqa: BLE001 - reported to the skill as a log line
        log(f"ERROR: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
